parameters:
  cache.service: cache.service

jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop


monolog:
    handlers:
        main:
            type:  test
            level: info

services:
   cache.service:
      class: CacheBundle\Service\MemoryCache
   cache.testservice:
        class: CacheBundle\Tests\CacheableClass
        tags:
            - { name: cacheable.service }
   annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader