parameters:
  cache.service: cache.service

jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop


monolog:
    handlers:
        main:
            type:  test
            level: info

services:
   cache.service:
      class: Symfony\Component\Cache\Adapter\ArrayAdapter
   cache.testservice:
        class: CacheBundle\Tests\CacheableClass
   cache.testservice.extended:
        class: CacheBundle\Tests\ExtendedCacheableClass
   annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader